import pickle
import numpy as np
import io
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
import streamlit as st

# ── 1.  MODEL YÜKLEME ALANI ───────────────────────────────────
try:
    model = pickle.load(open('model.pkl', 'rb'))
    scaler = pickle.load(open('scaler.pkl', 'rb'))
    model_loaded = True
except FileNotFoundError:
    st.error("⚠️ Model or Scaler files could not be found!")
    model_loaded = False

# ── 2.  TAHMİN FONKSİYONU ──────────────────────────────────────
def predict_insurance(age, sex, bmi, children, smoker, region):
    numerical_inputs = np.array([[age, bmi]])
    scaled_numerical = scaler.transform(numerical_inputs)
    age_scaled = scaled_numerical[0][0]
    bmi_scaled = scaled_numerical[0][1]

    sex_val = 1 if sex == "Female" else 0
    smoker_val = 1 if smoker == "Yes" else 0
    r_nw = 1 if region == "Northwest" else 0
    r_se = 1 if region == "Southeast" else 0
    r_sw = 1 if region == "Southwest" else 0

    final_features = np.array([[age_scaled, sex_val, bmi_scaled, children, smoker_val, r_nw, r_se, r_sw]])
    return model.predict(final_features)[0]

# ── 3.  PDF RAPORLAMA FONKSİYONU ───────────────────────────────
def generate_pdf_report(age, sex, bmi, children, smoker, region, result):
    """Generates a clean, professional, English-only PDF report."""
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=40, leftMargin=40, topMargin=40, bottomMargin=40)
    story = []
    styles = getSampleStyleSheet()

    primary_color = colors.HexColor("#085041")
    secondary_color = colors.HexColor("#1D9E75")

    title_style = ParagraphStyle('DocTitle', parent=styles['Heading1'], fontSize=24, textColor=primary_color, spaceAfter=6)
    sub_style = ParagraphStyle('DocSub', parent=styles['Normal'], fontSize=10, textColor=colors.HexColor("#475569"), spaceAfter=14)
    section_heading = ParagraphStyle('SecHeading', parent=styles['Heading2'], fontSize=14, textColor=primary_color, spaceBefore=10)

    story.append(Paragraph("HEALTH INSURANCE QUOTE REPORT", title_style))
    story.append(Paragraph("Generated by AI-Powered InsurTech Estimation System", sub_style))
    story.append(Spacer(1, 10))

    story.append(Paragraph("1. Customer Demographics & Lifestyle", section_heading))
    data_labels = [
        ["Age", str(age), "Gender", str(sex)],
        ["BMI", f"{bmi:.1f}", "Children", str(children)],
        ["Smoker Status", str(smoker), "Region", str(region)]
    ]
    t1 = Table(data_labels, colWidths=[130, 130, 130, 130])
    t1.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (0,-1), colors.HexColor("#f1f5f9")),
        ('BACKGROUND', (2,0), (2,-1), colors.HexColor("#f1f5f9")),
        ('TEXTCOLOR', (0,0), (-1,-1), colors.HexColor("#1e293b")),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor("#cbd5e1")),
        ('PADDING', (0,0), (-1,-1), 8),
    ]))
    story.append(t1)
    story.append(Spacer(1, 20))

    story.append(Paragraph("2. AI Financial Risk & Premium Estimation", section_heading))
    financial_data = [
        ["Calculation Metric", "Value ($)"],
        ["Estimated Annual Premium", f"${result:,.2f}"],
        ["Estimated Monthly Premium", f"${(result/12):,.2f}"]
    ]
    t2 = Table(financial_data, colWidths=[300, 220])
    t2.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (1,0), primary_color),
        ('TEXTCOLOR', (0,0), (1,0), colors.white),
        ('BACKGROUND', (0,1), (-1,-1), colors.HexColor("#f0faf6")),
        ('GRID', (0,0), (-1,-1), 0.5, secondary_color),
        ('PADDING', (0,0), (-1,-1), 10),
    ]))
    story.append(t2)
    story.append(Spacer(1, 25))

    footer_text = ("* Legal Notice: This document provides an artificial intelligence estimation based on historical health data. "
                   "It serves as a technical preview and does not constitute a final binding contract.")
    story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=styles['Normal'], fontSize=8, textColor=colors.HexColor("#64748b"))))

    doc.build(story)
    buffer.seek(0)
    return buffer